<?php

namespace Proxies\__CG__\Ecommerce\RestaurantBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Restaurant extends \Ecommerce\RestaurantBundle\Entity\Restaurant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'id', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'nomRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'photoRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'depRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'adresseRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'telRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'mailRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'fcbkRestaurant');
        }

        return array('__isInitialized__', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'id', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'nomRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'photoRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'depRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'adresseRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'telRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'mailRestaurant', '' . "\0" . 'Ecommerce\\RestaurantBundle\\Entity\\Restaurant' . "\0" . 'fcbkRestaurant');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Restaurant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomRestaurant($nomRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomRestaurant', array($nomRestaurant));

        return parent::setNomRestaurant($nomRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomRestaurant', array());

        return parent::getNomRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoRestaurant($photoRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoRestaurant', array($photoRestaurant));

        return parent::setPhotoRestaurant($photoRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoRestaurant', array());

        return parent::getPhotoRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepRestaurant($depRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepRestaurant', array($depRestaurant));

        return parent::setDepRestaurant($depRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepRestaurant', array());

        return parent::getDepRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseRestaurant($adresseRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseRestaurant', array($adresseRestaurant));

        return parent::setAdresseRestaurant($adresseRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseRestaurant', array());

        return parent::getAdresseRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelRestaurant($telRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelRestaurant', array($telRestaurant));

        return parent::setTelRestaurant($telRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelRestaurant', array());

        return parent::getTelRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailRestaurant($mailRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailRestaurant', array($mailRestaurant));

        return parent::setMailRestaurant($mailRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailRestaurant', array());

        return parent::getMailRestaurant();
    }

    /**
     * {@inheritDoc}
     */
    public function setFcbkRestaurant($fcbkRestaurant)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFcbkRestaurant', array($fcbkRestaurant));

        return parent::setFcbkRestaurant($fcbkRestaurant);
    }

    /**
     * {@inheritDoc}
     */
    public function getFcbkRestaurant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFcbkRestaurant', array());

        return parent::getFcbkRestaurant();
    }

}
