<?php

namespace Proxies\__CG__\Ecommerce\BoutiqueBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \Ecommerce\BoutiqueBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'id_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'nom_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'details_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'prix_unitaire', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'photo_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'id_typeproduit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'id_departement');
        }

        return array('__isInitialized__', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'id_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'nom_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'details_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'prix_unitaire', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'photo_produit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'id_typeproduit', '' . "\0" . 'Ecommerce\\BoutiqueBundle\\Entity\\Produit' . "\0" . 'id_departement');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduit', array());

        return parent::getIdProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomProduit($nomProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomProduit', array($nomProduit));

        return parent::setNomProduit($nomProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomProduit', array());

        return parent::getNomProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setDetailsProduit($detailsProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDetailsProduit', array($detailsProduit));

        return parent::setDetailsProduit($detailsProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getDetailsProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDetailsProduit', array());

        return parent::getDetailsProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrixUnitaire($prixUnitaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrixUnitaire', array($prixUnitaire));

        return parent::setPrixUnitaire($prixUnitaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrixUnitaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrixUnitaire', array());

        return parent::getPrixUnitaire();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoProduit($photoProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoProduit', array($photoProduit));

        return parent::setPhotoProduit($photoProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoProduit', array());

        return parent::getPhotoProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdTypeproduit($idTypeproduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdTypeproduit', array($idTypeproduit));

        return parent::setIdTypeproduit($idTypeproduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdTypeproduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdTypeproduit', array());

        return parent::getIdTypeproduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdDepartement($idDepartement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdDepartement', array($idDepartement));

        return parent::setIdDepartement($idDepartement);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdDepartement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdDepartement', array());

        return parent::getIdDepartement();
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', array());

        return parent::getContenu();
    }

}
