<?php

namespace Proxies\__CG__\Ecommerce\HotelBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Hotel extends \Ecommerce\HotelBundle\Entity\Hotel implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nomHotel', 'photosHotel', 'departementHotel', 'adresseHotel', 'telephoneHotel', 'mailHotel', 'facebookHotel');
        }

        return array('__isInitialized__', 'id', 'nomHotel', 'photosHotel', 'departementHotel', 'adresseHotel', 'telephoneHotel', 'mailHotel', 'facebookHotel');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Hotel $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomHotel($nomHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomHotel', array($nomHotel));

        return parent::setNomHotel($nomHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomHotel', array());

        return parent::getNomHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotosHotel($photosHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotosHotel', array($photosHotel));

        return parent::setPhotosHotel($photosHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotosHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotosHotel', array());

        return parent::getPhotosHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartementHotel($departementHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartementHotel', array($departementHotel));

        return parent::setDepartementHotel($departementHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartementHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartementHotel', array());

        return parent::getDepartementHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseHotel($adresseHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseHotel', array($adresseHotel));

        return parent::setAdresseHotel($adresseHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseHotel', array());

        return parent::getAdresseHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephoneHotel($telephoneHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephoneHotel', array($telephoneHotel));

        return parent::setTelephoneHotel($telephoneHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephoneHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephoneHotel', array());

        return parent::getTelephoneHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setMailHotel($mailHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMailHotel', array($mailHotel));

        return parent::setMailHotel($mailHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getMailHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMailHotel', array());

        return parent::getMailHotel();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookHotel($facebookHotel)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookHotel', array($facebookHotel));

        return parent::setFacebookHotel($facebookHotel);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookHotel()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookHotel', array());

        return parent::getFacebookHotel();
    }

}
