DefaultProduit:
    pattern:  /
    defaults: { _controller: EcommerceProduitBundle:Produit:index }

ajouteProduit:
    pattern:  /ajoute
    defaults: { _controller: EcommerceProduitBundle:Produit:ajouteProduit }

modifieProduit:
    pattern:  /modifie 
    defaults: { _controller: EcommerceProduitBundle:Produit:modifieProduit }

supprimeProduit:
    pattern:  /supprime{id} 
    defaults: { _controller: EcommerceProduitBundle:Produit:supprimeProduit }
    requirements:
      id:  \d+

voirProduit:
    pattern:  /details{id} 
    defaults: { _controller: EcommerceProduitBundle:Produit:detailsProduit }
    requirements:
      id:  \d+

listeProduit:
    pattern:  /liste 
    defaults: { _controller: EcommerceProduitBundle:Produit:listeProduit }