DefaultProduit:
    pattern:  /Produit
    defaults: { _controller: EcommerceProduitBundle:Produit:index }

AjouteProduit:
    pattern:  /Produit/ajoute
    defaults: { _controller: EcommerceProduitBundle:Produit:ajoutProduit }

modifieProduit:
    pattern:  /Produit/modifie 
    defaults: { _controller: EcommerceProduitBundle:Produit:modifieProduit }

supprimeProduit:
    pattern:  /Produit/supprime 
    defaults: { _controller: EcommerceProduitBundle:Produit:supprimeProduit }

listeProduit:
    pattern:  /Produit/liste 
    defaults: { _controller: EcommerceProduitBundle:Produit:listeProduit }