DefaultProduit:
    pattern:  /
    defaults: { _controller: EcommerceProduitBundle:Produit:index }

ajouteProduit:
    pattern:  /ajoute
    defaults: { _controller: EcommerceProduitBundle:Produit:ajouteProduit }

modifieProduit:
    pattern:  /modifie/{id}
    defaults: { _controller: EcommerceProduitBundle:Produit:modifieProduit }
    requirements:
      id:  \d+

supprimeProduit:
    pattern:  /supprime/{id} 
    defaults: { _controller: EcommerceProduitBundle:Produit:supprimeProduit }
    requirements:
      id:  \d+

voirProduit:
    pattern:  /voir/{id} 
    defaults: { _controller: EcommerceProduitBundle:Produit:voirProduit }
    requirements:
      id:  \d+

listeProduit:
    pattern:  /liste 
    defaults: { _controller: EcommerceProduitBundle:Produit:listeProduit }