parameters:
#    ecommerce_produit.example.class: Ecommerce\ProduitBundle\Example

services:
#    ecommerce_produit.example:
#        class: %ecommerce_produit.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
