<?php

namespace Ecommerce\DHotelBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DHotelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DHotelRepository extends EntityRepository
{
}
