<?php

namespace Ecommerce\ProduitBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeProduitRepository extends EntityRepository
{
}