EcommerceUserBundle:
    resource: "@EcommerceUserBundle/Controller/"
    type:     annotation
    prefix:   /user

HotelBundle:
    resource: "@HotelBundle/Controller/"
    type:     annotation
    prefix:   /hotel

EcommerceProduitBundle:
    resource: "@EcommerceProduitBundle/Resources/config/routing.yml"
    prefix:   /produit

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
