d_hotel:
    resource: "@DHotelBundle/Resources/config/routing.yml"
    prefix:   /hotel

ecommerce_boutique:
    resource: "@EcommerceBoutiqueBundle/Resources/config/routing.yml"
    prefix:   /boutique

ecommerce_user:
    resource: "@EcommerceUserBundle/Resources/config/routing.yml"
    prefix:   /

ecommerce_restaurant:
    resource: "@EcommerceRestaurantBundle/Resources/config/routing.yml"
    prefix:   /restaurant

ecommerce_culture:
    resource: "@EcommerceCultureBundle/Resources/config/routing.yml"
    prefix:   /culture

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#securite
fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix: /profile

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: /register

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /resetting
fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /change-password
