# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    encoders:
        Ecommerce\UserBundle\Entity\User: sha512
    providers:
        #in_memory:
         #   memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        # Firewall pour les pages de connexion, inscription, et récupération de mot de passe
        login:
            pattern: ^/(login$|register|resetting) # Les adresses de ces pages sont login, register et reset
            anonymous: true

        #pour le reste
        main:
            #anonymous: ~
            pattern: ^/ #tout ce qui commence par /
            form_login:  #notre methode d'authentification
                provider: fos_userbundle # on lit depuis le provier du haut
                remember_me: true #activer la possibilite de se souvenir de moi
            remember_me:
                key: %secret% # On définit la clé pour le remember_me (%secret% est un paramet
            anonymous: true # On autorise les utilisateurs anonymes (non identifiés)
            logout: true #On autorise la déconnexion manuelle (désactivé par défaut)

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }



    
